#!/usr/bin/env python3
"""Synchronize Alacritty with Amber's ten palettes.

Run at installation and on ThemeManager.selectedId change. No persistent watcher.
The generated theme is also imported by Alacritty on fresh starts.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BANK = ROOT / "shell/theme/palettes.json"
SELECTION = ROOT / "shell/theme/selection.json"
COLORS_FILE = ROOT / "config/alacritty/amber-colors.toml"
HEX = re.compile(r"#[0-9a-fA-F]{6}\Z")


def rgb(color: str) -> tuple[int, int, int]:
    if not isinstance(color, str) or not HEX.fullmatch(color):
        raise ValueError(f"Invalid hex color: {color!r}")
    return tuple(int(color[i:i + 2], 16) for i in (1, 3, 5))


def mix(left: str, right: str, portion: float) -> str:
    a, b = rgb(left), rgb(right)
    return "#" + "".join(f"{round((1 - portion) * x + portion * y):02X}" for x, y in zip(a, b))


def palette_for(name: str | None) -> dict:
    palettes = json.loads(BANK.read_text(encoding="utf-8"))
    if not isinstance(palettes, list) or not palettes:
        raise ValueError("Amber palettes.json is missing its palette list")
    if not name:
        try:
            selection = json.loads(SELECTION.read_text(encoding="utf-8"))
            name = selection.get("selected", "first-flame")
        except (OSError, ValueError, AttributeError):
            name = "first-flame"
    selected = next((p for p in palettes if p.get("id") == name), None)
    if selected is None:
        if name != "first-flame":
            raise ValueError(f"Unknown palette ID: {name}")
        selected = palettes[0]
    colors = selected["colors"]
    for role in ("background", "surface", "border", "muted", "accent", "text"):
        rgb(colors.get(role))
    return selected


def build_colors(palette: dict) -> dict[str, dict[str, str]]:
    c = palette["colors"]
    bg, surface, border, muted, accent, fg = (c[k] for k in
        ("background", "surface", "border", "muted", "accent", "text"))
    # Muted semantic ANSI tones, adapted gently to each Amber accent.
    base = {
        "red": mix("#B97870", accent, .16),
        "green": mix("#94AA83", accent, .15),
        "yellow": mix("#CEB176", accent, .34),
        "blue": mix("#839CAF", accent, .14),
        "magenta": mix("#AD90AD", accent, .15),
        "cyan": mix("#7FA6A5", accent, .17),
    }
    normal = {"black": mix(bg, "#090A0B", .28), **base, "white": fg}
    bright = {"black": muted, **{key: mix(value, fg, .23) for key, value in base.items()}, "white": fg}
    dim = {"black": bg, **{key: mix(value, bg, .52) for key, value in base.items()},
           "white": mix(fg, bg, .52)}
    return {
        "primary": {"background": bg, "foreground": fg,
                    "dim_foreground": muted, "bright_foreground": fg},
        "cursor": {"text": bg, "cursor": accent},
        "vi_mode_cursor": {"text": bg, "cursor": fg},
        "search.matches": {"foreground": bg, "background": accent},
        "search.focused_match": {"foreground": bg, "background": fg},
        "selection": {"text": fg, "background": mix(surface, accent, .22)},
        "normal": normal, "bright": bright, "dim": dim,
    }


def render(palette: dict, groups: dict[str, dict[str, str]]) -> str:
    out = [f"# Generated by Amber for palette: {palette['name']} ({palette['id']})",
           "# Do not edit directly. Change the Theme Bank selection instead.", ""]
    for section, values in groups.items():
        out.append(f"[colors.{section}]")
        out.extend(f'{key} = "{color}"' for key, color in values.items())
        out.append("")
    return "\n".join(out)


def write_if_changed(destination: Path, content: str) -> bool:
    if destination.is_file() and destination.read_text(encoding="utf-8") == content:
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=destination.parent,
                                     prefix=".amber-colors-", suffix=".tmp", delete=False) as temp:
        temp.write(content)
        temp_path = Path(temp.name)
    try:
        temp_path.replace(destination)
    finally:
        temp_path.unlink(missing_ok=True)
    return True


def ipc_update(groups: dict[str, dict[str, str]]) -> None:
    if not shutil.which("alacritty"):
        print("Amber: Alacritty is not on PATH; file colors are ready", file=sys.stderr)
        return
    overrides = [f'colors.{section}.{key}="{value}"'
                 for section, values in groups.items() for key, value in values.items()]
    try:
        result = subprocess.run(["alacritty", "msg", "config", "-w", "-1", *overrides],
                                text=True, capture_output=True, timeout=5, check=False)
        if result.returncode:
            # Expected if no Alacritty instance is running yet.
            print("Amber: colors written; no live Alacritty IPC connection available",
                  file=sys.stderr)
    except (OSError, subprocess.TimeoutExpired) as e:
        print(f"Amber: file updated but IPC unavailable: {e}", file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--palette", help="Explicit palette ID (otherwise reads selection.json)")
    parser.add_argument("--check", action="store_true", help="Validate and print palette, without writing")
    parser.add_argument("--no-ipc", action="store_true", help="Only update the TOML file")
    args = parser.parse_args()
    try:
        pal = palette_for(args.palette)
        groups = build_colors(pal)
        content = render(pal, groups)
        import tomllib
        tomllib.loads(content)  # validate produced TOML before touching files
        if args.check:
            print(f"Palette: {pal['name']} ({pal['id']})")
            print(f"Generated file: {COLORS_FILE}")
            print(f"TOML valid; {sum(len(v) for v in groups.values())} color entries")
            return 0
        changed = write_if_changed(COLORS_FILE, content)
        if changed:
            print(f"Amber Alacritty: applied {pal['name']}")
        if not args.no_ipc:
            ipc_update(groups)
        return 0
    except (OSError, ValueError, KeyError, TypeError) as e:
        print(f"Amber Alacritty: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
