#!/usr/bin/env python3
"""Amber -> Plasma 6 color scheme bridge. Standard library only.

This file is installed into <repo>/scripts/kde/sync_colors.py.
It deliberately does not configure KWin decorations.
"""
from __future__ import annotations
import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BANK = ROOT / 'shell/theme/palettes.json'
SELECTION = ROOT / 'shell/theme/selection.json'
COLOR_DIR = Path.home() / '.local/share/color-schemes'
HEX = re.compile(r'#[0-9a-fA-F]{6}\Z')
ROLES = ('background', 'surface', 'border', 'muted', 'accent', 'text')


def palettes() -> list[dict]:
    bank = json.loads(BANK.read_text(encoding='utf-8'))
    if not isinstance(bank, list) or len(bank) != 10:
        raise ValueError('Expected exactly 10 Amber palettes')
    ids = set()
    for item in bank:
        if not isinstance(item, dict):
            raise ValueError('Palette must be an object')
        ident = item['id']
        if not re.fullmatch(r'[a-z][a-z0-9-]*', ident) or ident in ids:
            raise ValueError(f'Invalid/duplicate palette ID: {ident!r}')
        ids.add(ident)
        for role in ROLES:
            if not HEX.fullmatch(item['colors'][role]):
                raise ValueError(f'Bad {role} color in {ident}')
    return bank


def scheme_id(p: dict) -> str:
    return 'Amber' + ''.join(word.title() for word in p['id'].split('-'))


def rgb(h: str) -> tuple[int, int, int]:
    return tuple(int(h[i:i+2],16) for i in (1,3,5))


def val(h: str) -> str:
    return ','.join(map(str, rgb(h)))


def blend(a: str, b: str, amount: float) -> str:
    c1, c2 = rgb(a),rgb(b)
    return '#' + ''.join(f'{round(v*(1-amount)+w*amount):02X}' for v,w in zip(c1,c2))


def colors_section(background: str, fg: str, alt: str, accent: str, muted: str) -> str:
    data = {
        'BackgroundNormal': background,
        'BackgroundAlternate': alt,
        'ForegroundNormal': fg,
        'ForegroundInactive': muted,
        'ForegroundActive': accent,
        'ForegroundLink': blend(accent, '#8DB6D4', 0.36),
        'ForegroundVisited': blend(accent, '#AE83B9', 0.34),
        'ForegroundNegative': '#CA776E',
        'ForegroundNeutral': '#D1A46C',
        'ForegroundPositive': '#9EAF89',
        'DecorationFocus': accent,
        'DecorationHover': blend(accent, fg, 0.25),
    }
    return '\n'.join(f'{k}={val(v)}' for k,v in data.items())


def render(p: dict) -> str:
    c = p['colors']
    bg, surface, border, muted, accent, fg = (c[x] for x in ROLES)
    sel_text = bg
    inactive_bg = blend(surface, bg, .40)
    inactive_fg = blend(muted, surface, .25)
    parts = [
        '# Generated by Amber KDE palette bridge. Do not edit directly.',
        f'# Palette source: shell/theme/palettes.json ; id={p["id"]}',
        '[General]',
        f'Name=Amber - {p["name"]}',
        f'ColorScheme={scheme_id(p)}',
        'shadeSortColumn=true',
        'TitlebarIsAccentColored=false',
        '',
        '[KDE]',
        'contrast=4',
        '',
    ]
    for name,bg_col,fg_col,alternate in [
        ('Window',bg,fg,surface),
        ('View',bg,fg,surface),
        ('Button',surface,fg,bg),
        ('Tooltip',surface,fg,bg),
        ('Complementary',surface,fg,bg),
        ('Header',surface,fg,bg),
        ('Selection',accent,sel_text,blend(accent,bg,.22)),
    ]:
        parts += [f'[Colors:{name}]',colors_section(bg_col,fg_col,alternate,accent,muted),'']
    parts += [
        '[Colors:Header][Inactive]',
        colors_section(inactive_bg,inactive_fg,bg,accent,muted),
        '',
        '[WM]',
        f'activeBackground={val(surface)}',
        f'activeForeground={val(fg)}',
        f'activeBlend={val(accent)}',
        f'inactiveBackground={val(inactive_bg)}',
        f'inactiveForeground={val(inactive_fg)}',
        f'inactiveBlend={val(border)}',
        '',
    ]
    return '\n'.join(parts)


def generate(bank: list[dict]) -> None:
    COLOR_DIR.mkdir(parents=True, exist_ok=True)
    for p in bank:
        dest = COLOR_DIR / f'{scheme_id(p)}.colors'
        if dest.is_symlink():
            raise RuntimeError(f'Symlink not allowed: {dest}')
        new_content = render(p)
        if not dest.exists() or dest.read_text(encoding='utf-8') != new_content:
            dest.write_text(new_content, encoding='utf-8')


def selected_id() -> str:
    try:
        return json.loads(SELECTION.read_text(encoding='utf-8')).get('selected','first-flame')
    except (OSError, ValueError, AttributeError):
        return 'first-flame'


def main() -> int:
    ap=argparse.ArgumentParser(description='Synchronize KDE Plasma colors with Amber Theme Bank')
    ap.add_argument('--check',action='store_true', help='Validate bank without changing anything')
    ap.add_argument('--generate',action='store_true', help='Regenerate all 10 .colors files only')
    ap.add_argument('--apply',metavar='PALETTE_ID',nargs='?',const='auto', help='Generate schemes and activate one')
    args=ap.parse_args()
    try:
        bank=palettes()
        if args.check or not (args.generate or args.apply):
            for p in bank: print(f'{p["id"]:21s} -> {scheme_id(p)}')
            print('Status: ready; no system changes.')
            return 0
        if args.apply and not shutil.which('plasma-apply-colorscheme'):
            raise RuntimeError('Command plasma-apply-colorscheme not installed')
        target = selected_id() if args.apply=='auto' else args.apply
        if args.apply is not None and target not in [p['id'] for p in bank]:
            raise ValueError(f'Unknown palette: {target!r}')
        generate(bank)
        if args.apply is not None:
            chosen=next(p for p in bank if p['id']==target)
            cmd=['plasma-apply-colorscheme',scheme_id(chosen)]
            result=subprocess.run(cmd,capture_output=True,text=True,timeout=20,check=False)
            if result.returncode:
                raise RuntimeError(f'Plasma returned {result.returncode}: {(result.stderr or result.stdout).strip()}')
            print(f'Applied: {scheme_id(chosen)}')
        else:
            print(f'Generated {len(bank)} KDE color schemes in {COLOR_DIR}')
        return 0
    except (OSError,ValueError,KeyError,TypeError,RuntimeError,subprocess.TimeoutExpired) as e:
        print(f'Amber KDE bridge: {e}',file=sys.stderr)
        return 1

if __name__=='__main__':
    raise SystemExit(main())
